#!/bin/bash

echo "🚀 AI Task Compiler Quick Start"
echo "=============================="
echo ""
echo "1. List available templates:"
echo "   python3 orchestrator/run.py --list-templates"
echo ""
echo "2. Create a simple utility function:"
echo "   python3 orchestrator/run.py --task \"function/utility:function_name=capitalize,function_description=Capitalizes first letter\""
echo ""
echo "3. Create a React component:"
echo "   python3 orchestrator/run.py --task \"feature/react-component:component_name=Button,category=common,component_description=Reusable button component\""
echo ""
echo "4. Run example workflow:"
echo "   python3 orchestrator/run.py --workflow orchestrator/example-workflow.json"
echo ""
echo "5. Dry run (see what would happen):"
echo "   python3 orchestrator/run.py --task \"function/utility:function_name=test\" --dry-run"
echo ""
echo "📝 Tips:"
echo "- Always test with --dry-run first"
echo "- Use --verbose for detailed output"
echo "- Check output/ directory for results"
echo "- Review logs/ for troubleshooting"
echo ""
echo "Ready to start? Try command #1 above!"