#!/bin/bash
# Auto-Claude GitHub Issue Processor
# Follows CLAUDE.md development standards

set -e

echo "🤖 Starting Auto-Claude Issue Processor"
echo "$(date): Processing GitHub issues with Claude Code CLI"

# Verify GitHub CLI is available and authenticated
if ! command -v gh &> /dev/null; then
  echo "❌ GitHub CLI not found in snapshot"
  exit 1
fi

if ! gh auth status &> /dev/null; then
  echo "❌ GitHub CLI not authenticated, trying token authentication..."
  if [ -n "$GITHUB_TOKEN" ]; then
    echo "$GITHUB_TOKEN" | gh auth login --with-token
    echo "✅ GitHub CLI authenticated with token"
  else
    echo "❌ No authentication available"
    exit 1
  fi
else
  echo "✅ GitHub CLI already authenticated"
fi

# Verify Claude CLI is available (should be pre-installed in snapshot)
if ! command -v claude &> /dev/null; then
  echo "❌ Claude CLI not found in snapshot"
  exit 1
fi

if ! claude auth status &> /dev/null; then
  echo "❌ Claude CLI not authenticated in snapshot"
  exit 1
fi

echo "✅ Claude CLI ready"

# Update to latest code (snapshot may be outdated)
echo "📥 Updating repository to latest..."
git fetch origin
git checkout main
git pull origin main

# Install/update dependencies if needed
if [ -f "package-lock.json" ]; then
  echo "📦 Updating dependencies..."
  npm ci
fi

# Get open issues with claude-task label
echo "🔍 Fetching open issues..."
ISSUES=$(gh issue list \
  --state open \
  --label "claude-task" \
  --json number,title,body,labels \
  --limit 1)

ISSUE_COUNT=$(echo "$ISSUES" | jq length)

if [ "$ISSUE_COUNT" -eq 0 ]; then
  echo "ℹ️ No issues found with 'claude-task' label"
  exit 0
fi

# Process the first issue
ISSUE_NUM=$(echo "$ISSUES" | jq -r '.[0].number')
ISSUE_TITLE=$(echo "$ISSUES" | jq -r '.[0].title')
ISSUE_BODY=$(echo "$ISSUES" | jq -r '.[0].body')

echo "🎯 Processing Issue #$ISSUE_NUM: $ISSUE_TITLE"

# Create working branch
BRANCH_NAME="auto/issue-$ISSUE_NUM"
git checkout -b "$BRANCH_NAME"

# Mark issue as in-progress
gh issue comment "$ISSUE_NUM" --body "🤖 **Auto-Claude Processing Started**

Started processing this issue automatically.
- Branch: \`$BRANCH_NAME\`
- Time: $(date)
- VPS: $(hostname)

Will create a PR if valid changes are generated."

# Create focused prompt for Claude
CLAUDE_PROMPT="Implement this GitHub issue for the bs-display project:

ISSUE #$ISSUE_NUM: $ISSUE_TITLE

$ISSUE_BODY

REQUIREMENTS:
- This is an Astro-based e-commerce platform for interactive displays
- Follow functional programming principles with TypeScript
- Follow existing patterns in /src/components/ and /src/development-standards/
- Create or modify files as needed to implement the requested feature
- Ensure TypeScript compilation passes

AUTOMATION CONTEXT:
- This is running automatically on a VPS
- Implement the most reasonable interpretation if unclear
- Follow established project conventions
- Work autonomously and make the necessary changes"

# Use Claude Code CLI to process the issue (with automation flags)
echo "🧠 Running Claude Code CLI with automation flags..."

# Debug: Show prompt length and first few lines
echo "📊 Prompt length: $(echo "$CLAUDE_PROMPT" | wc -c) characters"
echo "📝 First 3 lines of prompt:"
echo "$CLAUDE_PROMPT" | head -3
echo "..."

# Run Claude with --print for non-interactive automation and timeout
echo "⏳ Starting Claude CLI (with 10-minute timeout)..."
if timeout 600 claude --print --dangerously-skip-permissions --verbose "$CLAUDE_PROMPT" 2>&1 | tee /tmp/claude_output.log; then
  echo "✅ Claude Code CLI completed successfully"
  echo "📄 Output log size: $(wc -l < /tmp/claude_output.log) lines"
else
  CLAUDE_EXIT_CODE=$?
  echo "❌ Claude Code CLI failed (exit code: $CLAUDE_EXIT_CODE)"
  
  # Show last few lines of output for debugging
  echo "🔍 Last 10 lines of Claude output:"
  tail -10 /tmp/claude_output.log 2>/dev/null || echo "No output log available"
  
  # Check if it was a timeout
  if [ "$CLAUDE_EXIT_CODE" -eq 124 ]; then
    FAILURE_REASON="Claude CLI timed out after 10 minutes"
  else
    FAILURE_REASON="Claude CLI encountered an error (exit code: $CLAUDE_EXIT_CODE)"
  fi
  
  gh issue comment "$ISSUE_NUM" --body "🤖 **Processing Failed**

$FAILURE_REASON

This could mean:
- The issue requires manual intervention
- There was an unexpected error in the automation
- The request may need clarification
- Claude CLI hung or timed out

Please review the issue or try processing manually."
  
  # Clean up
  git checkout main 2>/dev/null || true
  git branch -D "$BRANCH_NAME" 2>/dev/null || true
  exit 1
fi

# Check if any changes were made
if git diff --quiet && git diff --cached --quiet; then
  echo "ℹ️ No changes generated by Claude"
  gh issue comment "$ISSUE_NUM" --body "🤖 **No Changes Generated**

Claude processed the issue but did not generate any code changes.
This could mean:
- The issue requires manual intervention
- The request was unclear or incomplete
- The issue is already resolved

Please review the issue requirements."
  
  # Clean up branch
  git checkout main
  git branch -D "$BRANCH_NAME"
  exit 0
fi

echo "✅ Changes detected, validating..."

# Run TypeScript check (following CLAUDE.md standards)
echo "🔍 Running TypeScript validation..."
if ! npm run check; then
  echo "❌ TypeScript validation failed"
  gh issue comment "$ISSUE_NUM" --body "🤖 **TypeScript Validation Failed**

Generated changes failed TypeScript validation. The issue may require manual intervention or more specific requirements.

Please review and provide additional context if needed."
  
  # Clean up
  git checkout main
  git branch -D "$BRANCH_NAME"
  exit 1
fi

# Run code review agent on modified files (following CLAUDE.md)
echo "📋 Running code review agent..."
MODIFIED_FILES=$(git diff --name-only HEAD~1)
for file in $MODIFIED_FILES; do
  if [[ "$file" =~ \.(tsx?|jsx?|astro)$ ]]; then
    echo "Reviewing: $file"
    if ! npm run tools:code-review -- --file "$file"; then
      echo "⚠️ Code review issues detected in $file"
    fi
  fi
done

# Commit changes with proper message format
echo "💾 Committing changes..."
git add .
git commit -m "feat: $ISSUE_TITLE

Auto-generated implementation using Claude Code CLI following project standards:
- Functional programming principles applied
- TypeScript validation passed
- Code review agent validation completed

Closes #$ISSUE_NUM

🤖 Generated with Claude Code on VPS
Co-Authored-By: Claude <noreply@anthropic.com>"

# Push branch
echo "📤 Pushing branch..."
git push origin "$BRANCH_NAME"

# Create PR with comprehensive description
echo "🔀 Creating Pull Request..."
PR_BODY="## 🤖 Automated Implementation

This PR was automatically generated by Claude Code CLI to address issue #$ISSUE_NUM.

## Changes Made
$(git log --oneline HEAD~1..HEAD)

## Validation Completed
- ✅ TypeScript validation passed (\`npm run check\`)
- ✅ Code review agent validation completed
- ✅ Follows functional programming standards
- ✅ Adheres to project component standards

## Issue Context
$ISSUE_BODY

---

**Automated Process Details:**
- Generated on VPS infrastructure
- Followed CLAUDE.md development standards
- Ready for human review and testing

Closes #$ISSUE_NUM"

gh pr create \
  --title "feat: $ISSUE_TITLE" \
  --body "$PR_BODY" \
  --label "automated" \
  --label "claude-generated"

# Get PR URL and update issue
PR_URL=$(gh pr view --json url -q .url)

gh issue comment "$ISSUE_NUM" --body "🤖 **Pull Request Created**

✅ Successfully generated implementation and created PR: $PR_URL

## Summary
- Changes generated using Claude Code CLI
- All validations passed (TypeScript, code review)
- Follows project development standards
- Ready for human review

The PR will be automatically linked to close this issue when merged."

echo "🎉 Successfully processed issue #$ISSUE_NUM"
echo "📋 Created PR: $PR_URL"