name: Test Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: startsWith(github.event.comment.body, '/test')
    runs-on: ubuntu-latest
    steps:
      - name: Test response
        run: |
          echo "Test workflow triggered by comment"
          echo "Comment: ${{ github.event.comment.body }}"
          
      - name: Post reply
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 Test workflow triggered successfully!'
            });